# Generated by Django 5.1.2 on 2024-10-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid4u', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_bid_allegro',
            name='status',
            field=models.CharField(default='Niewykonane', max_length=10),
        ),
        migrations.DeleteModel(
            name='Linked_account',
        ),
    ]
