# Generated by Django 5.1.2 on 2024-10-17 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid4u', '0002_list_bid_allegro_status_delete_linked_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_bid_allegro',
            name='owner',
        ),
        migrations.AddField(
            model_name='list_bid_allegro',
            name='account_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bid4u.account_allegro'),
        ),
    ]
