# Generated by Django 5.1.2 on 2024-10-17 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid4u', '0003_remove_list_bid_allegro_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_bid_allegro',
            name='account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bid4u.account_allegro'),
        ),
    ]
